import type { Entry } from "./config";

export type MockEntry = Omit<Entry, "rowNumber">;

export const mockEntries: MockEntry[] = [
    {
        registrationNumber: "23BCE10237",
        name: "Ananya Sharma",
        email: "ananya.sharma@example.com",
        phoneNumber: "9876543210",
        residencyStatus: "Hosteller",
        uniqueId: null,
        transactionId: "TXN-2025-0001",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE10458",
        name: "Rohan Gupta",
        email: "rohan.gupta@example.com",
        phoneNumber: "9823014456",
        residencyStatus: "Day Scholar",
        uniqueId: null,
        transactionId: "TXN-2025-0002",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE10692",
        name: "Meera Iyer",
        email: "meera.iyer@example.com",
        phoneNumber: "9912345678",
        residencyStatus: "Hosteller",
        uniqueId: null,
        transactionId: "TXN-2025-0003",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE10973",
        name: "Arjun Verma",
        email: "arjun.verma@example.com",
        phoneNumber: "9798123456",
        residencyStatus: "Day Scholar",
        uniqueId: null,
        transactionId: "TXN-2025-0004",
        mailSent: true,
    },
    {
        registrationNumber: "23BCE11021",
        name: "Neha Patel",
        email: "neha.patel@example.com",
        phoneNumber: "9123456789",
        residencyStatus: "Hosteller",
        uniqueId: null,
        transactionId: "TXN-2025-0005",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE11264",
        name: "Vikram Singh",
        email: "vikram.singh@example.com",
        phoneNumber: "9800123456",
        residencyStatus: "Day Scholar",
        uniqueId: null,
        transactionId: "TXN-2025-0006",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE11509",
        name: "Priya Nair",
        email: "priya.nair@example.com",
        phoneNumber: "9934567812",
        residencyStatus: "Hosteller",
        uniqueId: null,
        transactionId: "TXN-2025-0007",
        mailSent: true,
    },
    {
        registrationNumber: "23BCE11788",
        name: "Karan Mehta",
        email: "karan.mehta@example.com",
        phoneNumber: "9812345098",
        residencyStatus: "Day Scholar",
        uniqueId: null,
        transactionId: "TXN-2025-0008",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE11942",
        name: "Sana Khan",
        email: "sana.khan@example.com",
        phoneNumber: "9954321876",
        residencyStatus: "Hosteller",
        uniqueId: null,
        transactionId: "TXN-2025-0009",
        mailSent: false,
    },
    {
        registrationNumber: "23BCE12075",
        name: "Aditya Rao",
        email: "aditya.rao@example.com",
        phoneNumber: "9898765432",
        residencyStatus: "Day Scholar",
        uniqueId: null,
        transactionId: "TXN-2025-0010",
        mailSent: false,
    },
];
